apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-stack-prometheus:9090
    isDefault: true
    editable: true
    
  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://prometheus-stack-alertmanager:9093
    editable: true